max-gamma = 150

# >>> widget:schedule (managed by status_widgets.py hyprsunset-schedule)
profile {
    time = 07:30
    identity = true
}

profile {
    time = 21:00
    temperature = 4500
    gamma = 0.9
}
# <<< widget:schedule
